import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Check, Save, Shield, UserCog } from 'lucide-react';
import { Button } from '../components/ui/Button';
export function SettingsPage() {
    const [saved, setSaved] = useState(false);
    const handleSubmit = (event) => {
        event.preventDefault();
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
    };
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-2", children: [_jsx("span", { className: "inline-flex items-center gap-2 rounded-full bg-[#eef1ff] px-3 py-1 text-xs font-semibold text-allow-primary", children: "La tua area sicura" }), _jsx("h1", { className: "text-3xl font-bold text-slate-800", children: "Impostazioni semplici e trasparenti." }), _jsx("p", { className: "text-sm text-slate-500", children: "Qui controlli i tuoi dati, la sicurezza e le notifiche. Tutto spiegato con parole facili." })] }), _jsxs("form", { onSubmit: handleSubmit, className: "space-y-6", children: [_jsxs("section", { className: "rounded-3xl border border-slate-100 bg-white p-6 shadow-soft", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm font-semibold text-slate-700", children: [_jsx(UserCog, { className: "h-4 w-4 text-allow-primary" }), " Dati profilo"] }), _jsxs("div", { className: "mt-4 grid gap-4 md:grid-cols-2", children: [_jsxs("label", { className: "text-sm text-slate-600", children: ["Nome", _jsx("input", { type: "text", placeholder: "Mario Rossi", className: "mt-1 w-full rounded-2xl border border-slate-200 bg-[#f7f8fe] px-3 py-3 text-sm text-slate-700 outline-none focus:border-allow-primary" })] }), _jsxs("label", { className: "text-sm text-slate-600", children: ["Email", _jsx("input", { type: "email", placeholder: "mario@example.com", className: "mt-1 w-full rounded-2xl border border-slate-200 bg-[#f7f8fe] px-3 py-3 text-sm text-slate-700 outline-none focus:border-allow-primary", required: true })] })] })] }), _jsxs("section", { className: "rounded-3xl border border-slate-100 bg-white p-6 shadow-soft", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm font-semibold text-slate-700", children: [_jsx(Shield, { className: "h-4 w-4 text-allow-primary" }), " Privacy & sicurezza"] }), _jsxs("div", { className: "mt-4 grid gap-4 text-sm text-slate-500", children: [_jsx(Toggle, { label: "Richiedi 2FA all\u2019accesso", defaultChecked: true }), _jsx(Toggle, { label: "Invia report mensile cifrato via email" }), _jsx(Toggle, { label: "Abilita esportazione dati in formato GDPR", defaultChecked: true })] }), _jsx("p", { className: "mt-4 text-xs text-slate-400", children: "Allowday usa i tuoi dati solo per mostrarti il calendario. Puoi scaricarli o cancellarli quando vuoi." })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs(Button, { type: "submit", variant: "primary", className: "gap-2 rounded-2xl", children: [_jsx(Save, { className: "h-4 w-4" }), " Salva impostazioni"] }), saved ? (_jsxs("span", { className: "inline-flex items-center gap-1 rounded-full border border-[#4fb286]/30 bg-[#e3f8f5] px-3 py-1 text-xs font-semibold text-[#1d7a65]", children: [_jsx(Check, { className: "h-3.5 w-3.5" }), " Salvato!"] })) : null] })] })] }));
}
function Toggle({ label, defaultChecked }) {
    return (_jsxs("label", { className: "flex items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-[#f7f8fe] px-4 py-3", children: [_jsx("span", { className: "text-slate-600", children: label }), _jsx("input", { type: "checkbox", defaultChecked: defaultChecked, className: "h-5 w-10 rounded-full border border-slate-200 bg-white accent-allow-primary" })] }));
}
