import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { clsx } from 'clsx';
import { PiggyBank, ShieldCheck, Wallet, Coins } from 'lucide-react';
const statusStyles = {
    green: 'bg-[#e3f8f5] text-[#1d7a65] border-[#9bdac7]',
    yellow: 'bg-[#fff6e0] text-[#b68a12] border-[#f8d477]',
    red: 'bg-[#fee8ea] text-[#c2403d] border-[#f9a5a3]',
};
export function PlannerSummary({ plan }) {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: clsx('inline-flex w-fit items-center gap-2 rounded-full border px-4 py-2 text-xs font-semibold uppercase tracking-wide', statusStyles[plan.status]), children: ["Oggi sei: ", plan.statusLabel] }), _jsxs("div", { className: "grid gap-4 md:grid-cols-2 xl:grid-cols-4", children: [_jsx(SummaryCard, { icon: _jsx(Wallet, { className: "h-5 w-5" }), title: "Stipendio netto", value: `€ ${plan.monthlyIncome.toFixed(2)}`, subtitle: "Quello che incassi ogni mese." }), _jsx(SummaryCard, { icon: _jsx(ShieldCheck, { className: "h-5 w-5" }), title: "Spese fisse", value: `€ ${plan.recurring.toFixed(2)}`, subtitle: "Affitto, bollette, rate e costi certi." }), plan.extraSavings > 0 ? (_jsx(SummaryCard, { icon: _jsx(Coins, { className: "h-5 w-5" }), title: "Fondo extra", value: `€ ${plan.extraSavings.toFixed(2)}`, subtitle: "Savings aggiunti al piano." })) : null, _jsx(SummaryCard, { icon: _jsx(PiggyBank, { className: "h-5 w-5" }), title: "Quota consigliata", value: `€ ${plan.baseAmount.toFixed(2)}`, subtitle: "Questa \u00E8 la cifra serena per ogni giorno." })] }), _jsxs("p", { className: "text-sm text-slate-500", children: ["Per i prossimi ", plan.days, " giorni hai ", _jsxs("strong", { children: ["\u20AC ", plan.variableBudget.toFixed(2)] }), " da distribuire."] }), plan.spendApplied > 0 ? (_jsxs("p", { className: "rounded-2xl border border-[#e3f8f5] bg-[#f1faf8] px-4 py-3 text-sm text-slate-600", children: ["Hai registrato ", _jsxs("strong", { children: ["\u20AC ", plan.spendApplied.toFixed(2)] }), " di spese oggi. Ti restano", ' ', _jsxs("span", { className: plan.todayDelta >= 0 ? 'text-[#1d7a65] font-semibold' : 'text-[#c2403d] font-semibold', children: ["\u20AC ", Math.abs(plan.todayDelta).toFixed(2), " ", plan.todayDelta >= 0 ? 'di libertà' : 'di recupero'] }), "."] })) : (_jsx("p", { className: "rounded-2xl border border-[#eef1ff] bg-[#f7f8fe] px-4 py-3 text-sm text-slate-600", children: "Dopo aver registrato la spesa del giorno, Allowday colorer\u00E0 il calendario per te." }))] }));
}
function SummaryCard({ icon, title, value, subtitle }) {
    return (_jsxs("div", { className: "rounded-3xl border border-slate-100 bg-white p-5 shadow-soft", children: [_jsxs("div", { className: "flex items-center gap-3 text-xs font-semibold uppercase tracking-wide text-slate-400", children: [_jsx("span", { className: "grid h-9 w-9 place-items-center rounded-2xl bg-[#eef1ff] text-allow-primary", children: icon }), title] }), _jsx("p", { className: "mt-3 text-2xl font-semibold text-slate-800", children: value }), _jsx("p", { className: "mt-1 text-xs text-slate-400", children: subtitle })] }));
}
